### ISSUE TITLE
Add Reaper Linux Beta to the list of DAWs

### ISSUE THREAD

**Issue by diqidoq** [nodiscc/awesome-linuxaudio#30]
The long awaited Linux version of Reaper is on the BETA user testing stage and could be added here to the Midi and Audio DAWs maybe. While I am huge advocate for Ardour and Mixbus, I think it will be surely an enhancement for the Linux Audio eco system and has already good feedback. The original DAW was supporting OSX and Windows only before and was a successful Cubase replacement for many users, but has planned Linux support for a long time already. It's reputation is similar to Ardour and the development community is far more open than the one of BitWig (not a fan) and such.

Let me copy my link logs from our own teamportal notes over here for your reference:

- [Reaper Linux Wiki](https://wiki.cockos.com/wiki/index.php/REAPER_for_Linux)
- [Reaper Linux Download](https://www.landoleet.org/)
- [Reaper Linux SWS extension](https://stash.reaper.fm/32021/reaper_sws64.so.7z)
- [Reaper Linux announcement and forum thread](https://forum.cockos.com/showthread.php?s=c37256f2a368cf0bdb01ce51dd7d605c&t=193760)
- [Reaper Linux announcement on LinuxMusicians.com](https://linuxmusicians.com/viewtopic.php?f=24&t=15280&sid=8c3683ce703572a30c4e59fd2f410875&start=150)

**Comment by nodiscc** [comment]
Fixed in 753103af
