### ISSUE TITLE
VCVrack is sorted wrong

### ISSUE THREAD

**Issue by Luraktinus** [nodiscc/awesome-linuxaudio#32]
add it to the DAW section please

**Comment by nodiscc** [comment]
Pull Request welcome

**Comment by Luraktinus** [comment]
i have to look up how to do that, wait

**Comment by nodiscc** [comment]
* https://help.github.com/articles/editing-files-in-another-user-s-repository/
 * https://help.github.com/articles/creating-a-pull-request/
 * https://help.github.com/articles/using-pull-requests/

**Comment by Luraktinus** [comment]
it was easier than i thought... thank you
