### ISSUE TITLE
QLoud was moved

### ISSUE THREAD

**Issue by gaydenko** [nodiscc/awesome-linuxaudio#35]
QLoud was moved here:

https://github.com/molke-productions/qloud

I have added a link on the original page:

http://gaydenko.com/qloud/

**Comment by nodiscc** [comment]
@gaydenko can you send a pull request?

**Comment by gaydenko** [comment]
Sorry, I can not admit that formalism - I mean forking and pushing PR for the sake of a single line.

**Comment by nodiscc** [comment]
You just had to edit the file and click OK twice...
Anyway https://github.com/nodiscc/awesome-linuxaudio/commits/master

**Comment by gaydenko** [comment]
Thanks!
