### ISSUE TITLE
Add all u-he plugins

### ISSUE THREAD

**Issue by eingedanke** [nodiscc/awesome-linuxaudio#38]
Everything from u-he has a Linux VST version:
https://u-he.com/

Please add.

**Comment by nodiscc** [comment]
@eingedanke I don't have much time to maintain the project right now. Can you send a patch adding u-he plugins?

See https://help.github.com/articles/editing-files-in-another-user-s-repository/ and https://help.github.com/articles/using-pull-requests/ if you need help editing the file/sending a Pull Request. Basically

 * Login to Github
 * Go to https://github.com/nodiscc/awesome-linuxaudio/blob/master/README.md
 * Click the edit button
 * Add u-he plugins with the proper syntax (copy another entry to use as an example)
 * In the "Commit change" provide a descriptive message (eg. "Add u-he plugins")
 * Select "create pull request" and follow the instructions.

Thank you
