### ISSUE TITLE
Add "Olive" (Video)

### ISSUE THREAD

**Issue by Symbian9** [nodiscc/awesome-linuxaudio#48]
- https://github.com/olive-editor/olive

**Comment by nodiscc** [comment]
@Symbian9 can you add it? The process is described [here](https://github.com/nodiscc/awesome-linuxaudio/blob/master/CONTRIBUTING.md). Let me know if something is unclear.

Olive looks like a good video editor. Have you tried it? Any idea of how it compares to Kdenlive/Openshot/... ?

**Comment by nodiscc** [comment]
Moved to https://gitlab.com/nodiscc/awesome-linuxaudio/-/issues/6
