### ISSUE TITLE
U-He ZebraHZ

### ISSUE THREAD

**Issue by ahellquist** [nodiscc/awesome-linuxaudio#51]
ZebraHZ is a custom version of U-he Zebra that is part of a soundset made by Hans Zimmer  and Howard Scarr
It is avaliable as Linux binary so it should be included in the list IMO
You need a Zebra license to purchase the ZebraHZ version

 https://u-he.com/products/soundsets/zebra2-soundsets.html

**Comment by nodiscc** [comment]
@ahellquist can you add it? The process is described [here](https://github.com/nodiscc/awesome-linuxaudio/blob/master/CONTRIBUTING.md). Let me know if something is unclear.

**Comment by nodiscc** [comment]
Moved to https://gitlab.com/nodiscc/awesome-linuxaudio/-/issues/3
