### ISSUE TITLE
Pianoteq from modartt

### ISSUE THREAD

**Issue by ahellquist** [nodiscc/awesome-linuxaudio#52]
Commercial physical modeled acoustic and electric pianos

both 32 and 64bit LV2 and also arm binaries available

https://www.modartt.com/pianoteq

**Comment by nodiscc** [comment]
@ahellquist can you add it? The process is described [here](https://github.com/nodiscc/awesome-linuxaudio/blob/master/CONTRIBUTING.md). Let me know if something is unclear.

**Comment by nodiscc** [comment]
Moved to https://gitlab.com/nodiscc/awesome-linuxaudio/-/issues/2
