### ISSUE TITLE
add u-he plugins

### ISSUE THREAD

**Issue by nodiscc** [nodiscc/awesome-linuxaudio#7]
http://www.kvraudio.com/forum/viewtopic.php?f=31&t=424953 non-free?

**Comment by Atavic** [comment]
tyrelln6 [DOWNLOAD LINUX VERSION „TYRELL N6 V3.0 REV 389“](https://www.amazona.de/freeware-synth-tyrell-n6-v3-03/)

[Podolski for Linux (rev 2758)](http://www.kvraudio.com/forum/viewtopic.php?p=5869503)

**Comment by nodiscc** [comment]
Repro-1 has been added and is currently the only u-he plugin with native linux VST support
