### ISSUE TITLE
Some descriptions are in French

### ISSUE THREAD

**Issue by Calinou** [nodiscc/awesome-linuxaudio#9]
> audacity - Éditeur audio rapide multi plate-forme (Homepage)

Why is Audacity's description in French?

**Comment by nodiscc** [comment]
See TODO https://github.com/nodiscc/awesome-linuxaudio#todo

> re-run dwlink -mb with LANG=C to get packages descriptions in english

There are several descriptions in french, because i originally ran `dwlink -mb packagename` with `LANG=fr_FR.utf8`. If you want to submit a patch for this I'd merge it.
